name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install backend deps
        working-directory: ./backend
        run: npm ci
      - name: Run backend linter (if configured)
        working-directory: ./backend
        run: echo "No linter configured"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install frontend deps
        working-directory: ./frontend
        run: npm ci
      - name: Run frontend build
        working-directory: ./frontend
        run: npm run build
